apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsapitest33023
  labels:
    app: jsapitest33023
  namespace: jsapitest33023-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsapitest33023
  template:
    metadata:
      labels:
        app: jsapitest33023
    spec:
      containers:
        - name: jsapitest33023
          image: crazk8sehiebdpdv2i7fmty6.azurecr.io/jsapitest33023:latest
          ports:
            - containerPort: 3000