apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-4-5-23-run2
  labels:
    app: jokes-4-5-23-run2
  namespace: jokes-4-5-23-run2-ns2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokes-4-5-23-run2
  template:
    metadata:
      labels:
        app: jokes-4-5-23-run2
    spec:
      containers:
        - name: jokes-4-5-23-run2
          image: crcrplaneazk8s4i7zlvwos5tsldzdw.azurecr.io/jokes-4-5-23-run2:latest
          ports:
            - containerPort: 3000