apiVersion: apps/v1
kind: Deployment
metadata:
  name: apideploytest33023
  labels:
    app: apideploytest33023
  namespace: apideploytest33023-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apideploytest33023
  template:
    metadata:
      labels:
        app: apideploytest33023
    spec:
      containers:
        - name: apideploytest33023
          image: crazk8sehiebdpdv2i7fmty6.azurecr.io/apideploytest33023:latest
          ports:
            - containerPort: 3000