apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0418-fix2
  labels:
    app: test0418-fix2
  namespace: namespace-workflow-1681836363433
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0418-fix2
  template:
    metadata:
      labels:
        app: test0418-fix2
    spec:
      containers:
        - name: test0418-fix2
          image: acrworkflow1681836363433.azurecr.io/image-workflow-1681836363433:latest
          ports:
            - containerPort: 3000