apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0418-bug
  labels:
    app: test0418-bug
  namespace: namespace-workflow-1681825823766
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0418-bug
  template:
    metadata:
      labels:
        app: test0418-bug
    spec:
      containers:
        - name: test0418-bug
          image: acrworkflow1681825823766.azurecr.io/image-workflow-1681825823766:latest
          ports:
            - containerPort: 3000