apiVersion: v1
kind: Service
metadata:
  name: test0418-fix
  namespace: namespace-workflow-1681835883753
spec:
  type: LoadBalancer
  selector:
    app: test0418-fix
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000