apiVersion: v1
kind: Service
metadata:
  name: apideploytest33023
  namespace: apideploytest33023-ns
spec:
  type: LoadBalancer
  selector:
    app: apideploytest33023
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000